#!/bin/sh

# Title:         fsc (Flowbite-Svelte-CLI)
# Description:   List Flowbite-Svelte components and its props
# Author:        Shinichi Okada <okada.shin@gmail.com>
# Date:          2022-03-20

set -eu
VERSION="0.1.0"
SCRIPT_NAME=$(basename "$0")

# Set variables
PROJECT_DIR=$(pwd)
MYFILE="flowbite_svelte_components"
MODULE_DIR="${PROJECT_DIR}/node_modules/flowbite-svelte"
PACKAGEFILE="${MODULE_DIR}/package.json"

# Keep readlinkf function
readlinkf() {
    [ "${1:-}" ] || return 1
    max_symlinks=40
    CDPATH='' # to avoid changing to an unexpected directory

    target=$1
    [ -e "${target%/}" ] || target=${1%"${1##*[!/]}"} # trim trailing slashes
    [ -d "${target:-/}" ] && target="$target/"

    cd -P . 2>/dev/null || return 1
    while [ "$max_symlinks" -ge 0 ] && max_symlinks=$((max_symlinks - 1)); do
        if [ ! "$target" = "${target%/*}" ]; then
            case $target in
            /*) cd -P "${target%/*}/" 2>/dev/null || break ;;
            *) cd -P "./${target%/*}" 2>/dev/null || break ;;
            esac
            target=${target##*/}
        fi

        if [ ! -L "$target" ]; then
            target="${PWD%/}${target:+/}${target}"
            printf '%s\n' "${target:-/}"
            return 0
        fi
        link=$(ls -dl -- "$target" 2>/dev/null) || break
        target=${link#*" $target -> "}
    done
    return 1
}

self=$(readlinkf "$0")
script_dir=${self%/*}
# For Debian APT remove line 7 to 38 and use the following line to
# define the script_dir
# script_dir="/usr/share/shellscript_template"

# Import files
# shellcheck disable=SC1091
{
    . "${script_dir}/lib/getoptions.sh"
    . "${script_dir}/lib/main_definition.sh"
    . "${script_dir}/lib/utils.sh"
    # import only one of helpers file
    . "${script_dir}/lib/shell_helpers.sh"
    # or
    # . "${script_dir}/lib/bash_helpers.sh"
}

# Keep it. You need this for main parser.
eval "$(getoptions parser_definition parse "$0") exit 1"
parse "$@"
eval "set -- $REST"

if [ $# -gt 0 ]; then
    MYLINE=$(jq '.exports' "${PACKAGEFILE}" | awk '/\/.*\/.*:/{
    gsub(/"/,"",$0)
    gsub(/,$/,"",$0)
    nf=split ($0,array,".svelte:")
    ni=split (array[1],subarray,"/")
    print subarray[ni],array[2]
    }' | grep -iw "$1")
    # echo $MYLINE
    FILE_PATH="${MODULE_DIR}/${MYLINE##* ./}"
    # echo $FILE_PATH
    bannerColor "$1 props are " "blue" "*"
    grep "export let" "${FILE_PATH}"
    exit 0
else
    bannerColor 'All component names: ' "green" "*"
    jq '.exports' "${PACKAGEFILE}" | awk '/\/.*\/.*:/{
    gsub(/"/,"",$0)
    gsub(/,$/,"",$0)
    nf=split ($0,array,".svelte:")
    ni=split (array[1],subarray,"/")
    print subarray[ni],array[2]
    }'| tee "${MYFILE}"
    exit 0
fi
